"""added compare_type =True for tracking db.column changes

Revision ID: 280865097c99
Revises: 1027ed0b1e78
Create Date: 2020-08-05 15:59:27.339318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '280865097c99'
down_revision = '1027ed0b1e78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=120),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###
